version: '3'
networks:
  server:

services:
  server:
      build: ./server/
      restart: on-failure
      networks:
        - server
      environment:
        droneHost: "drone"
      volumes:
        - ./darknet:/darknet
        - ./frames:/frames
  drone:
      build: .
      restart: on-failure
      depends_on:
        - server
      ports:
        - 9090:9090
      networks:
        - server